# Generated by Django 5.2 on 2026-05-06 09:24

import oscar.models.fields.autoslugfield

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
