# Generated by Django 5.2 on 2026-05-07 08:03

import oscar.models.fields.autoslugfield
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='title', unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', unique=True),
        ),
    ]
